on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Get time
        id: get-date
        run: |
          echo ::set-output name=date::$(/bin/date -u "+%Y%m%d")
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          npm install
          node main.js
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-date.outputs.date }}
          release_name: Release ${{ steps.get-date.outputs.date }}
          draft: false
          prerelease: false
      - name: Upload Release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: './DUMMY.*.deb'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
